### ISSUE TITLE
Wreck Spawning not in corners of maps ( Circle / Rect )

### ISSUE THREAD

**Issue by LtJulius** [Wyqer/A3-Scripts#1]
Hey,
just a little mistake in the script while fetching all roads.

If you want to get all roads from the center you will need a other size based on the diagonal of a quad.
[`_roadsArray = _center nearRoads (_size/2);`](https://github.com/Wyqer/A3-Scripts/blob/master/kp_wreckspawn.sqf#L69)

should be
`_roadsArray = _center nearRoads (_size / (sqrt 2));`

Will fix the problem, that the corners of a map are empty of wrecks.

With friendly regards,
LtJulius

**Comment by Wyqer** [comment]
Oh, you're right.
I've just "tested" it on maps like Altis and Tanoa, where the corners of the maps are water, so I've not thought about that.

Many thanks for the hint, really appreciated :)
