### ISSUE TITLE
kp_distancemonitor

### ISSUE THREAD

**Issue by anfo55** [Wyqer/A3-Scripts#2]
Hello again
I originally requested you create this script and am very happy that was fuilfilled. However I neglected to properly check if it worked for its intended role correctly. Since the script was originally intended to work for a soldier walking (or running) in a straight line and measure that distance, the player walking backwards or sideways should **not** be included in the measurement.

May I request the script only measures forward movement please?

**Comment by Wyqer** [comment]
Not without massively extending the code, sorry.
