### ISSUE TITLE
kp_distancemonitor - Possible to only show 100m marks?

### ISSUE THREAD

**Issue by AVESUM** [Wyqer/A3-Scripts#3]
Excellent small script working like a charm! User case for my community would be to use it with compass bearings in hard terrain. Would it be possible to only show updates at every hundred meters traveled?

**Comment by Wyqer** [comment]
If you want it only update when it hits the next 100 mark you can change the script at this position:
https://github.com/KillahPotatoes/KP-A3-Scripts/blob/master/kp_distancemonitor.sqf#L55

to this:
```
hint format ["Travelled Distance:\n%1%2m",(floor (kp_distance / 100)), "00"];
```
